// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJi_f6XVzDJ1jQJ1Zc7VXaue1N-ccfy0',
    appId: '1:108180484089:android:f22c51ea321fe18b04d728',
    messagingSenderId: '108180484089',
    projectId: 'talab-e6638',
    storageBucket: 'talab-e6638.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeui-aKtLhPyg_jIBw8CAlhFL4A7E54ZQ',
    appId: '1:108180484089:ios:366adeae02c80bc404d728',
    messagingSenderId: '108180484089',
    projectId: 'talab-e6638',
    storageBucket: 'talab-e6638.firebasestorage.app',
    androidClientId:
        '108180484089-3d98dmohbghiqm4mj4i8dpgcnpbvebqu.apps.googleusercontent.com',
    iosClientId:
        '108180484089-i86oapgt2k55rvbloliguutja4ht9khm.apps.googleusercontent.com',
    iosBundleId: 'com.talab.white',
  );
}
